# Generated by Django 6.0.3 on 2026-03-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barstock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='units_per_item',
            field=models.IntegerField(default=1, help_text='Number of individual units in one inventory item (e.g., units per carton/bottle)'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_carton',
            field=models.BooleanField(default=False, help_text='Whether this item is sold by carton/multi-unit package'),
        ),
    ]
