# Generated by Django 6.0.3 on 2026-04-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barstock', '0002_auto_20260318_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('momo', 'Mobile Money'), ('pending', 'Pending')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='paid', max_length=10),
        ),
    ]
