# Generated by Django 6.0.3 on 2026-04-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barstock', '0003_sale_payment_method_sale_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
